### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by longyi11111** [pyDraco9/Dota2-Jianghu-Script#1]
看起来是易语言的结构，不太会用，能QQ联系你请教一下用法吗？

**Comment by longyi11111** [comment]
![image](https://user-images.githubusercontent.com/87059562/193171975-e0b7ce49-e45a-4d6d-8b34-d7277ad4844e.png) 按照图片配置了界面仍然无法启动，提示界面异常

**Comment by longyi11111** [comment]
改了分辨率进去之后，游戏启动后， 脚本程序直接闪退，没任何日志信息

**Comment by pyDraco9** [comment]
在"_启动窗口"代码中"全局_注册码"配置大漠的注册码。
游戏启动后的检测部分在“游戏进程检测”函数内。
你的截图“窗口大小异常”是配置分辨率错误，正确配置是1600*900。
游戏检测成功后大漠绑定，并进入“脚本主体”函数执行图色识别。
脚本本身是在独立线程中运行的，不应该影响主线程的程序，闪退可能是其他原因造成的（如是否使用了有问题的大漠或模块），或者检查是否因为DownCpu()不支持造成的其他问题。
建议插入调试信息并调试运行查看具体闪退的位置。

**Comment by pyDraco9** [comment]
> 

确认了一下，因为设计时没有考虑“使用错误的大漠注册码”，才会导致游戏启动后因为以上原因，导致程序闪退。

已更新，请务必使用正确的大漠注册码。

**Comment by Mr-Fengalang** [comment]
大佬留个联系方式呗 我最近想学习写三国世界的脚本 刚接触脚本 不太会用 想像你请教请教
